### ISSUE TITLE
E_SERVER_ERROR when trying to access /dev/dependencies

### ISSUE THREAD

**Issue by mbret** [niftylettuce/email-templates#137]
It seems that this route is based on what exist in app package.json.

The problem is that in rare case you may have a problem with your node packages and in my example one package was not present in node_modules or someone forgot to npm install.
line: 'get /dev/dependencies':

I think you should catch and handle an not existing node_module even if it's present inside package.json or even better display a message for the user to let him know that the package is in default.

**Comment by jeduan** [comment]
Thanks! Interesting issue, what was the package that was not installed?

**Comment by mbret** [comment]
email-template which require node-gyp. The install failed on my windows because I don't have python. Well it also doesn't install next packages because of this fail. Anyway it could be anything else, the package is not relevant to this issue I think :)
