### ISSUE TITLE
Set default template engine

### ISSUE THREAD

**Issue by david-cahill** [niftylettuce/email-templates#138]
Hi there,

Is it possible to set a default template engine? I'd like to remove the .ejs file extension from my template files and just use <template-name>.html

**Comment by jeduan** [comment]
Hi! That feature is not currently supported.

**Comment by VinceOPS** [comment]
Hi,

This would be nice to have the ".html" extension available!

Or at least, template-manager could use `renderDefault` when `engineMap` does not contain the target extension (in our case, `'html'`).

Thanks for your work!

**Comment by niftylettuce** [comment]
see v3.x, there's docs to swap engines <https://github.com/niftylettuce/email-templates#custom-template-engine-eg-ejs
