### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by m0ser** [niftylettuce/email-templates#140]
More of a question, but is there an easy way to use this without a "templateDir" and file i/o?  Streams perhaps?  

Thanks.

**Comment by jeduan** [comment]
Not right now, but definitely something to think about.

**Comment by dynnamitt** [comment]
:+1:

**Comment by Zambonilli** [comment]
On a similar note, has there been any interest in using cloud file systems like s3?  This project seems perfect for our requirements but we have multiple nodes that send email and keeping a local file system in sync across nodes and systems is a pain relative to a shared cloud drive.

I could fork and do a PR on this and get support for streams which would indirectly allow clients to stream their cloud directories.

**Comment by jeduan** [comment]
A PR that supports streams would be great!

**Comment by niftylettuce** [comment]
@Zambonilli any luck?

**Comment by Zambonilli** [comment]
Sorry, I had a kid... I don't have the free time I used to so I probably won't be able to help out here until I get a weekend alone.  Let me check my schedule.
