### ISSUE TITLE
Promises don't resolve when using SCSS

### ISSUE THREAD

**Issue by nathanjohnson320** [niftylettuce/email-templates#142]
Hi all,

I copied code from the newsletter example template and when I call Promise.all built from the below code. If i comment out the report.render function the promises resolve fine but when I add it in they don't resolve.

```
return report.render(testResults).then(function (results) {

            // setup e-mail data
            var mailOptions = {
                from: 'Test <test@test.com>', // sender address
                to: recipients, // list of receivers
                subject: 'Test', // Subject line
                html: results.html
            };

            // send mail with defined transport object
            return transporter.sendMailAsync(mailOptions);
        }).catch(function(err) {
            console.log(err);
        });
```

I know this is an issue with SCSS because I have an css version that works properly.

**Comment by acedward** [comment]
+1 had same issue.
Converted scss to css and it started working.

**Comment by row1** [comment]
Try changing it to:
```javascript
report.render(Object.assign({}, testResults)).then(function (results) {
```
If that works then it is the same issue as #167

**Comment by niftylettuce** [comment]
you may want to use v3.x now
