### ISSUE TITLE
Nested templates

### ISSUE THREAD

**Issue by Kuzmin** [niftylettuce/email-templates#145]
When writing HTML emails, I usually have a layout.html.hbs that is the same for all emails, and inside it has a `{{ content }}` that contains the content that is specific for this email (signup/login/password reset, other transactional emails). Is there any way you could support this type of nested emails/template inheritance or whatever you would like to call it?

I would love to move to your library, it seems very well thought out!

**Comment by faceleg** [comment]
I'm looking to do the same with nunjucks, which uses:

`{% extend template_path %}`

**Comment by row1** [comment]
For Handlebars you can try using https://github.com/shannonmoeller/handlebars-layouts

**Comment by davidfurlong** [comment]
this `include` (ejs) or `extend` (handlebars) doesn't seem to work with localization... disappointing, as componentialization & composition is the corner stone of good code bases.

**Comment by Kuzmin** [comment]
@davidfurlong: Could you explain some more how the code you are trying to run looks? Without a code sample it's hard to guess how your code is broken.

**Comment by davidfurlong** [comment]
@Kuzmin yep ofcourse.

```js
// base/en/html.ejs
<html>
<body>
Company name,
<img />
<%- include(pathToTemplate, data) %>
</body>
</html>
```

```js
// welcome/en/html.js
<span>Welcome to the site, <%= name %></span>
```

```js
const locale = "en";
new EmailTemplate('../base').render({
  pathToTemplate: '../welcome',
 data: {
   name: "David"
 },
}, locale)
```

**Comment by davidfurlong** [comment]
This sort of paradigm does not play nicely with a) localization b) text/html files. I found a way around and documented it here https://github.com/crocodilejs/node-email-templates/issues/225. But this solution is verbose and doesn't leverage this library very well. Want to keep my templates DRY

**Comment by Kuzmin** [comment]
I don't know about ejs but I know that Handlebars allows you to define custom functions. Sounds like it should be possible for you to create your own function myInclude (or something), that handles locales in template paths and corrects the path. 

Eg pass the path as /some/path/$LOC/welcome.html and let the method do string replacement :)
