### ISSUE TITLE
Use juiceResources and transform inlined resources

### ISSUE THREAD

**Issue by dantman** [niftylettuce/email-templates#148]
Issues like #35 and #135 make it apparent that the `style.*` pattern and use of `inlineContent` is problematic. You only get one stylesheet source. `@media` queries don't get embedded from that source. You can't control where that source comes from to share styles. And you can't use a file to embed client hacks that rely on selectors. Not directly a result of this but it's also worth noting that while you can transform things like .less files you also cannot add things like postcss transforms into the flow.

The most obvious fix to most of these is to make use of `juiceResources` which inlines linked resources and deprecate the style.\* pattern in favour of inlining styles from stylesheet `<link>`s.

This fixes most of those issues, however there is one issue with it in that this pattern does not directly support having resources such as `.less` files and other preprocessed css syntaxes transformed before being inlined.

Technically this isn't hard to deal with outside of node-email-template. You just run the step of transforming any preprocessed styles into a .css file first. However ideally the replacement for `style.*` would have the same level of support for preprocessors.

---

I do have an idea of how to support preprocessors in a way that would work with `juiceResources`. Additionally it would work with multiple inlined resources even with different preprocessors.

The `type=""` on `<link>` and `<style>` tags could be used to declare that a resource is something other than css and what preprocessor to use.

For example:

``` html
<link rel="stylesheet" type="text/less" href="style.less">
```

Would inline `style.less` and transform it with LESS.

As a bonus we could even consider supporting some `data-*` attributes for configuring the transform. LESS actually already has a few of these (when you're using a client side transform) such as `data-global-vars='{ myvar: "#ddffee", mystr: "\"quoted\"" }'`.

Other transforms like postcss will still be a problem. However implementing this kind of transform handling will probably require some changes to juice that will involve a filter in juiceOptions that could be used to apply other transformations without `node-email-templates`' involvement.

**Comment by scottmas** [comment]
Like you said, something like this is absolutely essential in order to be able to add media queries and selector client hacks.

Wouldn't a simpler solution simply to be to insert the compiled version of style.[ext] into html.[ext] as a style tag? Then the developer can simply specify in juiceOptions if he wants the juice option `preserveMediaQueries` and `removeStyleTags` and everything works as desired.

**Comment by niftylettuce** [comment]
see v3.x https://github.com/niftylettuce/email-templates#automatic-inline-css-via-stylesheets
