### ISSUE TITLE
Send mail without creating .html file

### ISSUE THREAD

**Issue by lajpatshah** [niftylettuce/email-templates#150]
Is there a way like nodemailer in which I can directly send the compiled body instead of saving it in result.html?

**Comment by alejandromagnorsky** [comment]
+1

**Comment by niftylettuce** [comment]
Can you give an example @lajpatshah @alejandromagnorsky?  This doesn't make sense.

**Comment by alejandromagnorsky** [comment]
@niftylettuce I have an CMS where the user can modify an HTML template that is then stored in the DB as a string. Later, I query the DB to retrieve that string and, after "compiling" it, I send it as an email.

**Comment by TrueMan777** [comment]
How do you guys create that result.html? I can't make it appearing anywhere. The .render() produce HTML correctly though. Do I need to create a file with the output manually?

**Comment by alejandromagnorsky** [comment]
@niftylettuce, any update for this? In nodemailer they allow it but their template engine is not powerful enough (it doesn't allow condition or iteration like this plugin).

Thanks.

**Comment by alejandromagnorsky** [comment]
I ended up using lodash templates and setting it as the renderer in the nodemailer template configuration.

**Comment by sumpton** [comment]
@alejandromagnorsky thanks for mentioning lodash. I use it frequently and did not realize how useful it is for simple templates. It looks great for some of our notifications.

**Comment by alejandromagnorsky** [comment]
@sumpton, you are welcome! 
Yes, lodash is really cool and it's templates are very powerful too.

**Comment by niftylettuce** [comment]
see v3.x - we even have https://github.com/niftylettuce/preview-email built in
