### ISSUE TITLE
Can I have shared CSS styles between templates?

### ISSUE THREAD

**Issue by tomsoderlund** [niftylettuce/email-templates#157]
...or do I need to have a `style.[ext]` in each template folder?

**Comment by andylibrian** [comment]
Hi @niftylettuce, or @jeduan 

I'm encountering this as well. I have many email templates which share the same style.
I'm avoiding to duplicate the same `style.[ext]` to each folder.

I propose the introduction of an option to share a global style file.
It can be places in these lines, if `style.[ext]` file is not present in template directory, then it checks if an option `this.options.sharedStyleFile` (or something) is present.

https://github.com/niftylettuce/node-email-templates/blob/master/src/email-template.js#L55-L58

Let me know if you think it's a good idea, I could send a Pull Request.
If not, do you have any alternative?

Thanks.

**Comment by jssuttles** [comment]
SCSS is awesome. Try it out.

**Comment by andylibrian** [comment]
Hi @jssuttles the example here https://github.com/niftylettuce/node-email-templates/tree/master/examples/templates still need style.scss inside every template folder. Can we use only a single shared file without having style.scss in every folder?

**Comment by jssuttles** [comment]
I don't know if this is a hack to you, but I have style.scss in every folder with only one line.
@import '../common';
Then, everything shares the common.scss file which exists outside of the individual template folders.

**Comment by jssuttles** [comment]
That way you can still have special per email CSS but you also have common CSS shared by all templates.

**Comment by andylibrian** [comment]
Thanks @jssuttles I'll go that way.

**Comment by Starscream27** [comment]
Thanks @jssuttles, that's a clean solution ! I had been looking for something like that

**Comment by niftylettuce** [comment]
see https://github.com/niftylettuce/email-templates#automatic-inline-css-via-stylesheets and use v3.x
