### ISSUE TITLE
{ [Error: timedout while connecting to smtp server] code: 4, smtp: undefined }

### ISSUE THREAD

**Issue by llvc** [niftylettuce/email-templates#158]
After installing emailjs, I run the following code for mailing in nodejs
emailjs = require('emailjs');

var server = emailjs.server.connect({
        user:"mygmail.com",
        password:"gmail password",
        host:"smtp.gmail.com",
        ssl:true,
        port: 465
      });

 server.send({
          text: "message",
          from:"LLVC <sender email>",
          to:"<receiver email>",
          subject:"Subject"
        },
        function (err, message) {
        console.log(err || message);
    });

when running the script, I got a error 
{ [Error: timedout while connecting to smtp server] code: 4, smtp: undefined }
I want to fix them.
Thanks

**Comment by jeduan** [comment]
You timed out while connecting to the SMTP server.
