### ISSUE TITLE
Changelog Updates

### ISSUE THREAD

**Issue by akohout** [niftylettuce/email-templates#163]
Is there any reason you stopped filling your Changelog on new releases? Would help me/others when updating your library in projects.

**Comment by jeduan** [comment]
Lack of time. It would be very welcome if you submit a PR with this.

**Comment by niftylettuce** [comment]
@akohout if you can update changelog that'd be awesome 💃

**Comment by westy92** [comment]
Can this please be revisited?  It's critical to know of any breaking changes when upgrading from v2 to v3.

**Comment by niftylettuce** [comment]
@westy92 one moment I'll push the section that documents the v2 to v3 upgrade.

**Comment by niftylettuce** [comment]
@westy92 Please see <https://github.com/niftylettuce/email-templates#v3-breaking-changes>

**Comment by niftylettuce** [comment]
@westy92 note that I am releasing v3.0.8 which has backwards compatible 2.x support for the options `juiceOptions` and `disableJuice`.
