### ISSUE TITLE
Create text version from html version

### ISSUE THREAD

**Issue by rightaway** [niftylettuce/email-templates#165]
For simple cases, is it possible to have the text version be created from the html version automatically (e.g. by stripping the html tags), or allowing for integration with https://www.npmjs.com/package/html-to-text. Otherwise anytime you make a change to the text in one you'd need to keep it in sync between both files. For cases where the messages are simple and would be identical minus the html tags such functionality would be useful.

**Comment by pstadler** [comment]
Although this can be achieved manually after rendering just the html version, I'd be happy to see this automatically done whenever a text version is absent.

**Comment by row1** [comment]
It would definitely need to be "opt-in". I am using 'html-to-text' in my 'node-email-templates' pipeline and like to register different Handlebar partials before doing a text conversion and render.

**Comment by niftylettuce** [comment]
I use `html-to-text` as well and don't have any issues, are you guys still needing this option somehow?  If so, a pull request would be instantly accepted I'm sure 👍

**Comment by niftylettuce** [comment]
see v3.x
