### ISSUE TITLE
subject.ejs not rendering

### ISSUE THREAD

**Issue by joum** [niftylettuce/email-templates#173]
I have a simple ejs template to place a var in a string to use as subject, but when I pass it in the object to templateSender it doesn't show up. The HTML works ok. Can anyone help me sort this out?

**Comment by niftylettuce** [comment]
I haven't reproduced this - can you share code or did you still not find the fix?

**Comment by joum** [comment]
I'm sorry, but I'm not working with your code anymore - the project I was involved in came to a stop a while ago.

Unfortunately, I also currently don't have access to my codebase at that time. Wish I could be of more assistance.

As far as I'm concerned, you can close this and I suggest that if anyone else has the same issue, they should open other item.

Good job! Keep it up!

**Comment by FdezRomero** [comment]
Hi @niftylettuce, I'm having the same problem as @joum rendering a Nunjucks subject template. The template is really simple, loaded from a localized external file.

Template (`templates/email/invitation/es/subject.njk`):
```nunjucks
Invitación para {{ notification.list.name }}
```

But it only renders:
```
Invitación
```

Relevant code:
```
var invitationTemplate = new EmailTemplate(path.resolve(__dirname, '../templates/email/invitation'));

  invitationTemplate.render(notif.data, notif.data.user.language, (err, results) => {

    if (err) {
      return done(err);
    }

    smtp.sendMail({
      from: `"${notif.data.user.username}" <no-reply@domain.com>`,
      replyTo: `"${notif.data.user.username}" <${notif.data.user.email}>`,
      to: notif.data.user.email,
      subject: results.subject,
      html: results.html
    }, (err, response) => {

      if (err) {
        return done(err);
      }

      return done(null, response);

    });

  });
```

Do I need to surround the subject line with quotes or something? Thanks!

**Comment by niftylettuce** [comment]
not sure how nunjucks syntax works.  honestly I became truly disappointed with nunjucks after using it for almost a year and switched back to pug, closing this.  see v3.x.
