### ISSUE TITLE
cache templates?

### ISSUE THREAD

**Issue by santimacia** [niftylettuce/email-templates#178]
Does the plugin cache the template render for future use like express does using in production mode?

I find jade/pug very slow to re-render each time

**Comment by niftylettuce** [comment]
I don't believe it caches.  @santimacia would you care to submit a pull request after you fork/clone this repository locally and check into this?  We'd gladly appreciate some help from the community.

**Comment by StephanHoyer** [comment]
try https://github.com/tutory/email-templates-as-promised

**Comment by albertosouza** [comment]
It only cache file content but not compiled template. see in https://github.com/crocodilejs/node-email-templates/blob/master/src/email-template.js#L55

**Comment by niftylettuce** [comment]
see v3.x and also <https://github.com/ladjs/cache-pug-templates>

there is example in README for caching pug templates in particular:
https://github.com/niftylettuce/email-templates#cache-pug-templates
