### ISSUE TITLE
Consider removing some devDependencies in package.json

### ISSUE THREAD

**Issue by myyellowshoe** [niftylettuce/email-templates#179]
I've installed handlebars as my template. But still get lots of warning messages telling me it's unable to resolve some modules. the consolidate package required by this module is giving me lots of similar messages.

Unable to resolve some modules:
  "emblem" in /Users/administrator/Dropbox/Development/hubbble/hubbblewww/node_modules/email-templates/lib/template-manager.js (os.osx.x86_64)
  "less" in /Users/administrator/Dropbox/Development/hubbble/hubbblewww/node_modules/email-templates/lib/template-manager.js (os.osx.x86_64)
  "stylus" in /Users/administrator/Dropbox/Development/hubbble/hubbblewww/node_modules/email-templates/lib/template-manager.js (os.osx.x86_64)
  "styl" in /Users/administrator/Dropbox/Development/hubbble/hubbblewww/node_modules/email-templates/lib/template-manager.js (os.osx.x86_64)
  "node-sass" in /Users/administrator/Dropbox/Development/hubbble/hubbblewww/node_modules/email-templates/lib/template-manager.js (os.osx.x86_64)
If you notice problems related to these missing modules, consider running:

  meteor npm install --save emblem less stylus styl node-sass
...

No real problems i've experienced from this, just largely an unnecessary extra message when I have what's needed. I'd imagine its probably better that they are removed from dev depenencies, instead of adding extra bulk to package.json.

**Comment by jeduan** [comment]
Those packages are needed to run tests while developing the module. They are also required only when they are used… I wonder what might be going on here.

**Comment by myyellowshoe** [comment]
Gotcha, i figured it was something like that. Could consider using optional dependencies: https://docs.npmjs.com/files/package.json#optionaldependencies

**Comment by niftylettuce** [comment]
@myyellowshoe still an issue?  any luck finding out solution?

**Comment by niftylettuce** [comment]
v3.x released
