### ISSUE TITLE
`If` conditions not evaluated

### ISSUE THREAD

**Issue by mikaoelitiana** [niftylettuce/email-templates#185]
I am using email templates with some conditions inside but they are not evaluated. Variables are correctly replaced but both block of and `if ... else ... endif` are shown. 

<img width="879" alt="capture d ecran 2016-07-18 a 16 53 22" src="https://cloud.githubusercontent.com/assets/674667/16917005/63842326-4d08-11e6-8e36-0ee73de5b075.png">

I have tried with different template engines but the result is the same (atpl, twig, nunjucks).

**Comment by niftylettuce** [comment]
@mikaoelitiana Can you please share your full code example?
