### ISSUE TITLE
using the word `client` as a key in the locals breaks template rendering

### ISSUE THREAD

**Issue by slackincode** [niftylettuce/email-templates#196]
I have run into a very strange bug when rendering templates using a key of `client` as one of the locals variables.  I have narrowed it down to the following breaking test:

``` javascript
const EmailTemplate = require('email-templates').EmailTemplate;
const path = require('path')

var templateDir = path.join(__dirname, 'clienttest')

var newsletter = new EmailTemplate(templateDir)
var locals = {client: 'Joe'}

newsletter.render(locals, function (err, result) {
  if (err) {
    throw err;
  }
  console.log(result.html);
})
```

and the following ejs files:
**clienttest/html.ejs**

``` html
<%- include('./includedFile'); %>

<strong>Hello World</strong>
```

**clienttest/includedFile.ejs**

``` html
<strong>Included File Success</strong>
```

You get an error of

```
TypeError: /Users/testuser/dev/testapp/clienttest/html.ejs:1
 >> 1| <%- include('./includedFile'); %>
    2| 
    3| <strong>Hello World</strong>
    4| 

include is not a function
    at eval (eval at <anonymous> (/Users/testuser/dev/testapp/node_modules/ejs/lib/ejs.js:495:12), <anonymous>:49:16)
```

The error is erroneous as it has nothing to do with the `include` as you can see by changing the key from `client` to anything else (like `cats`, or `unicorns`).

**Comment by niftylettuce** [comment]
I think client is a reserved key by jade, not sure if it is still anymore, anyways v3.x is released, see the README of this repo
