### ISSUE TITLE
Prototype methods of the locals object are not available in templates

### ISSUE THREAD

**Issue by frenya** [niftylettuce/email-templates#201]
When trying to pass an object to the rendering function, no prototype methods are available in the template. Similar problem occurs when passing a mongoose.js object with virtual properties - none of them are available it the template.

It seems that the following code in `email-template.js` (introduced in 2.3.1) is to blame:

``` javascript
    } else if (locals) {
      locals = assign({}, locals)
    }
```

since it replaces the original object with a new prototype-less one.

**Comment by jeduan** [comment]
What's the use case?

**Comment by frenya** [comment]
I thought my original description summed it up, but apparently not enough :(

I ran into this when rendering a mongoose.js object through a jade/pug template. The object has a couple of persistent properties (think "firstName", "lastName" - stored in MongoDB) and a couple of virtual/computed ones (think "fullName"). When passing this to Jade through email-templates, the "fullName" property is not available.

Is it clearer now?

**Comment by niftylettuce** [comment]
I don't recommend using virtuals with mongoose.  Closing this.
