### ISSUE TITLE
Database driven templates

### ISSUE THREAD

**Issue by ekoome** [niftylettuce/email-templates#217]
For ease of maintaining templates, how can I use this module with templates stored in a database? At the moment, the API requires I pass a directory with templates.

**Comment by liftyourgame** [comment]
I'm happy to work on this if ok with crocodile

**Comment by niftylettuce** [comment]
we'd be happy to have your contributions @liftyourgame 

feel free to join slack if you'd like to chat or need any help, or just want to bounce ideas

http://slack.crocodilejs.com

**Comment by niftylettuce** [comment]
This has been added in v3.x, see <https://github.com/niftylettuce/email-templates#custom-rendering-eg-from-a-mongodb-database>.  Does this satisfy your needs?
