### ISSUE TITLE
How can I configure formatjs?

### ISSUE THREAD

**Issue by rochapablo** [niftylettuce/email-templates#221]
I'm trying to use https://formatjs.io/handlebars/ (# Using Named Number Formats), and they set the config like this:

```
var intlData = {
    locales: 'en-US'
}

var context = {
    price: 1000
};

var html = template(context, {
    data: {intl: intlData}
});
```

So, using ```new EmailTemplate(path)```, where do I can set ```data: {intl: intlData}```?

I'm asking, because I've tried many things, but nothing seems to work (https://github.com/yahoo/handlebars-intl/issues/86).

**Comment by niftylettuce** [comment]
try v3.x?
