### ISSUE TITLE
Missing modules for v3.0

### ISSUE THREAD

**Issue by gbourne1** [niftylettuce/email-templates#238]
When running the new v3.0 example I get errors because of missing modules: 
babel-runtime
sharp

Adding these two modules fixes the dependencies:
npm install --save babel-runtime
npm install --save sharp

**Comment by niftylettuce** [comment]
Will fix this shortly, I already see the culprit and that is <https://github.com/ladjs/nodemailer-base64-to-s3>

**Comment by niftylettuce** [comment]
@gbourne1 Can you please try `npm install --save email-templates@3.0.2`?  v3.0.2 should have resolved this.  I completely rewrote <https://github.com/ladjs/nodemailer-base64-to-s3> to fix this.

**Comment by niftylettuce** [comment]
Actually, I'm going to just publish v3.0.3 without this package built in.  People probably don't need this.

**Comment by gbourne1** [comment]
Removed modules: sharp and babel-runtime. Version 3.0.2 looks good.  Nice work!

**Comment by niftylettuce** [comment]
@gbourne1 try v3.0.3 - it has built-in email preview now using <https://github.com/niftylettuce/preview-email>

**Comment by gbourne1** [comment]
Looks good!
