### ISSUE TITLE
EmailTemplate is not a constructor

### ISSUE THREAD

**Issue by dottodot** [niftylettuce/email-templates#241]
I've required using 

```
const EmailTemplate = require('email-templates').EmailTemplate;
```
and the following
```
const template = new EmailTemplate('email_templates/my_template');
```
gives an error of 

> EmailTemplate is not a constructor

v2.7.1 doesn't have this issue but I've not tried anything in-between that release and the latest one.

**Comment by niftylettuce** [comment]
Read the documentation please, v3 has a different API than v2.

**Comment by niftylettuce** [comment]
@dottodot did you see https://github.com/niftylettuce/email-templates#v3-breaking-changes yet?

**Comment by dottodot** [comment]
Yes sorry got it working now thanks.
