### ISSUE TITLE
Doesn't re renders when locals changes

### ISSUE THREAD

**Issue by sallomendo** [niftylettuce/email-templates#252]
I don't know if I'm the only one getting this bug, but once you send an initial email the subsequent emails don't get updated locals, so it renders the same as the initial.

I think it has to do with https://github.com/niftylettuce/email-templates/blob/master/index.js#L137

**Comment by niftylettuce** [comment]
I will have this fixed today. When I release a new version to NPM I will ping you. Also feel free to join our Slack at http://slack.crocodilejs.com/.

**Comment by niftylettuce** [comment]
Please install v3.0.9 from NPM.  `npm install email-templates@latest` or `yarn add email-templates@latest` - this issue is fixed and tests have been written as well to ensure.  Any further issues please open a new issue, and thanks again for reporting.

**Comment by sallomendo** [comment]
Awesome, thanks!
