### ISSUE TITLE
Set locale for mail with i18n

### ISSUE THREAD

**Issue by lludol** [niftylettuce/email-templates#259]
Hello,

Can you write on your README that we have to set the "locale" attribute in the "locals" Object to the current locale to use the right language ?

```javascript
email.send({
  template: 'mars',
  message: {
    to: 'elon@spacex.com'
  },
  locals: {
    locale: 'fr', // THIS
    name: 'Elon'
  }
}).then(console.log).catch(console.error);
```

I had to read your code to find out how it works!

By the way, thank you for your work!

**Comment by niftylettuce** [comment]
thanks @lludol for bringing this to my attention, I've updated the README

does this look OK to you?

<https://github.com/niftylettuce/email-templates#localization>
