### ISSUE TITLE
Address object

### ISSUE THREAD

**Issue by polalegria** [niftylettuce/email-templates#262]
Hello,

I am trying to configure the **message**, the problem is that the **from** does not let me add a name to the address.

```js
const email = new Email({
  message: {
    from: '"Custom Name" no-reply@mail.com'
  },
  transport: transporter
});
```

I have read the configuration of nodemailer ([https://nodemailer.com/message/addresses/](https://nodemailer.com/message/addresses/)) and they assure that it works. 

Can you help me?
Thanks.

**Comment by niftylettuce** [comment]
@polalegria should the format not be `from: 'Custom Name <no-reply@mail.com>'`?

it looks like there's a test that should satisfy your use case though, https://github.com/nodemailer/nodemailer/blob/master/test/addressparser/addressparser-test.js#L72-L73 -- perhaps its an issue with addressparser?

**Comment by polalegria** [comment]
@niftylettuce i tried this options:

```
from: 'Custom Name <no-reply@mail.com>',
from: '"Custom Name" <no-reply@mail.com>',
from: 'Custom Name no-reply@mail.com'
```

And any works for me...
Addressparser is inside nodemailer, really?

**Comment by niftylettuce** [comment]
yes it used to be in its own module, unfortunately i think the maintainer
found it easier and more manageable to have it all in one package and
repo.  if this issue is fixed please close it?

**Comment by polalegria** [comment]
@niftylettuce thanks for your helping.
