### ISSUE TITLE
Error: Cannot find module 'juice'

### ISSUE THREAD

**Issue by hugodes** [niftylettuce/email-templates#263]
I've tried updating from v2 to v3 but apparently v3 depends on a 'juice' module that is not in email-templates own depedencies. Do you want me to submit a PR with this feature or is it this way on purpose ?

**Comment by hugodes** [comment]
Seems I'm not the only one #248

**Comment by niftylettuce** [comment]
@hugodes which version of email-templates are you using?  please use the latest if you can.  `npm install email-templates@latest` or `yarn add email-templates@latest`.  juice is in fact a listed dependency in the project if you look at <https://github.com/niftylettuce/email-templates/blob/master/package.json#L22-L23>.  there was a bug in an older version of 3.x that had this issue.

**Comment by niftylettuce** [comment]
@hugodes if this is still an issue please comment here again with more info including what version of node and what version of email-templates you are using.  thanks!

**Comment by hugodes** [comment]
@niftylettuce  I'm using 3.1.7 , node 8.9.1 (LTS)

**Comment by niftylettuce** [comment]
@hugodes can you try reinstalling?  it should be OK, `juice` is listed as a dep.  try clearing and reinstalling your node modules?

**Comment by hugodes** [comment]
I've node so, rm -rf node_modules && npm install (with this line in my package.json:     "email-templates": "^3.1.7",

**Comment by niftylettuce** [comment]
@hugodes what is the version that gets installed in node_modules?  can you open `node_modules/email-templates/package.json` and share the version?  also feel free to join our Slack channel if you'd rather ping me there to help figure out this weird issue.

**Comment by hugodes** [comment]
`{
  "_args": [
    [
      "email-templates@3.1.7",
      "/Users/hugodes/src/core/corejs"
    ]
  ],
  "_from": "email-templates@3.1.7",
  "_id": "email-templates@3.1.7",
  "_inBundle": false,
  "_integrity": "sha512-qaev+07u7czIDAVoCPT/8RZcDZZPe9FA/ezaYHcIJagAJI6e/DHujBGmCGje+Z0PTaLoS0SmKVXeI5WcjWF/Kg==",
  "_location": "/email-templates",
  "_phantomChildren": {
    "async": "2.5.0",
    "chalk": "1.1.3",
    "cheerio": "0.22.0",
    "commander": "2.9.0",
    "cross-spawn": "5.1.0",
    "datauri": "1.0.5",
    "graceful-fs": "4.1.11",
    "htmlparser2": "3.9.2",
    "lodash.unescape": "4.0.1",
    "mensch": "0.3.3",
    "ms": "2.0.0",
    "request": "2.83.0",
    "slick": "1.12.2",
    "universalify": "0.1.1",
    "valid-data-url": "0.1.4",
    "xtend": "4.0.1"
  },
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "email-templates@3.1.7",
    "name": "email-templates",
    "escapedName": "email-templates",
    "rawSpec": "3.1.7",
    "saveSpec": null,
    "fetchSpec": "3.1.7"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/email-templates/-/email-templates-3.1.7.tgz",
  "_spec": "3.1.7",
  "_where": "/Users/hugodes/src/core/corejs",
  "author": {
    "name": "Nick Baugh",
    "email": "niftylettuce@gmail.com",
    "url": "http://niftylettuce.com"
  },
  "bugs": {
    "url": "https://github.com/niftylettuce/email-templates/issues",
    "email": "niftylettuce@gmail.com"
  },
  "contributors": [
    {
      "name": "Nick Baugh",
      "email": "niftylettuce@gmail.com",
      "url": "http://niftylettuce.com"
    }
  ],
  "dependencies": {
    "@ladjs/i18n": "^0.0.5",
    "auto-bind": "^1.1.0",
    "consolidate": "^0.14.5",
    "debug": "^3.1.0",
    "fs-extra": "^4.0.2",
    "get-paths": "^0.0.2",
    "html-to-text": "^3.3.0",
    "juice": "^4.2.0",
    "juice-resources-promise": "^0.0.2",
    "lodash.defaultsdeep": "^4.6.0",
    "lodash.isempty": "^4.4.0",
    "lodash.isfunction": "^3.0.8",
    "lodash.isobject": "^3.0.2",
    "lodash.isstring": "^4.0.1",
    "lodash.merge": "^4.6.0",
    "lodash.omit": "^4.5.0",
    "nodemailer": "^4.1.3",
    "preview-email": "^0.0.6"
  },
  "description": "Create, preview, and send custom email templates for Node.js. Highly configurable and supports automatic inline CSS, stylesheets, embedded images and fonts, and much more! Made for sending beautiful emails with Lad.",
  "devDependencies": {
    "ava": "^0.22.0",
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "cheerio": "^1.0.0-rc.2",
    "codecov": "^2.3.0",
    "cross-env": "^5.0.5",
    "eslint": "^4.8.0",
    "eslint-config-prettier": "^2.6.0",
    "eslint-plugin-prettier": "^2.3.1",
    "husky": "^0.14.3",
    "lint-staged": "^4.2.3",
    "nyc": "^11.2.1",
    "prettier": "^1.7.4",
    "pug": "^2.0.0-rc.4",
    "remark-cli": "^4.0.0",
    "remark-preset-github": "^0.0.7",
    "xo": "^0.19.0"
  },
  "engines": {
    "node": ">=6.4.0"
  },
  "files": [
    "lib",
    "locales"
  ],
  "homepage": "https://github.com/niftylettuce/email-templates",
  "keywords": [
    "email",
    "lad",
    "lass",
    "koa",
    "pug",
    "consolidate",
    "template",
    "templates",
    "engine",
    "postmark",
    "sendgrid",
    "mailchimp",
    "mandrill",
    "transport",
    "nodemailer",
    "moonmail",
    "mailgun"
  ],
  "license": "MIT",
  "lint-staged": {
    "*.{js,jsx,mjs,ts,tsx,css,less,scss,json,graphql}": [
      "prettier --write --single-quote --trailing-comma none",
      "git add"
    ],
    "*.md": [
      "remark . -qfo",
      "git add"
    ]
  },
  "main": "lib/index.js",
  "name": "email-templates",
  "remarkConfig": {
    "plugins": [
      "preset-github"
    ]
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/niftylettuce/email-templates.git"
  },
  "scripts": {
    "build": "babel src --out-dir lib",
    "coverage": "nyc report --reporter=text-lcov > coverage.lcov && codecov",
    "lint": "xo && remark . -qfo",
    "precommit": "lint-staged && npm test",
    "test": "npm run build && npm run lint && npm run test-coverage",
    "test-coverage": "cross-env NODE_ENV=test nyc ava",
    "watch": "babel src --watch --out-dir lib"
  },
  "version": "3.1.7",
  "xo": {
    "extends": "prettier",
    "plugins": [
      "prettier"
    ],
    "parserOptions": {
      "sourceType": "script"
    },
    "rules": {
      "prettier/prettier": [
        "error",
        {
          "singleQuote": true,
          "bracketSpacing": true,
          "trailingComma": "none"
        }
      ],
      "max-len": [
        "error",
        {
          "code": 80,
          "ignoreUrls": true
        }
      ],
      "capitalized-comments": "off",
      "camelcase": "off",
      "no-warning-comments": "off"
    },
    "space": true
  }
}
`

I'll join you on slack

**Comment by hugodes** [comment]
@niftylettuce what's your handle on slack ?

**Comment by niftylettuce** [comment]
im niftylettuce on Slack

http://slack.crocodilejs.com

**Comment by climberwoodi** [comment]
Experience the same problem...

**Comment by niftylettuce** [comment]
@climberwoodi can you try `yarn clean email-templates` or `npm clean email-templates` to see if that resolves issue?

**Comment by niftylettuce** [comment]
I haven't been able to reproduce and the Travis-CI tests are all passing so I'm guessing this is a local/cache only issue.

I'd suggest upgrading `npm install -g npm` if you need, but if you have further information on how to reproduce please let me know.

**Comment by sean-hill** [comment]
@niftylettuce I'm facing this same issue using `email-templates` `^3.3.3` which has a `juice` dependency of `^4.2.2`. After running `npm install` from my root project, the `juice` dependency is apparently not being added to my `node_modules`.
