### ISSUE TITLE
Text Only?

### ISSUE THREAD

**Issue by willbutler** [niftylettuce/email-templates#265]
There was a 2.x issue related to requiring a HTML template. Is there a configuration option in 3.x that I'm missing to force an email to only render using the text template?

**Comment by niftylettuce** [comment]
@willbutler I'm looking into this now for you.

**Comment by niftylettuce** [comment]
Sorry @willbutler haven't had time yet, I will try to look at this soon though

**Comment by niftylettuce** [comment]
Adding this now @willbutler!

**Comment by niftylettuce** [comment]
Please try v3.3.0+ @willbutler!  See the updated [README instructions here](https://github.com/niftylettuce/email-templates#text-only-email-no-html) for information on the new `textOnly` Boolean option.  **By default if there is only a `text` template file in the template folder than it will only use that.**  But if you have both text/html template files in a template folder, then you'll need to pass `textOnly: true` to explicitly only have a text-based version of the email.

```sh
npm install email-templates@latest
```

or with yarn:

```sh
yarn add email-templates@latest
```
