### ISSUE TITLE
Dependency coffee-script fails to install

### ISSUE THREAD

**Issue by biiit** [niftylettuce/email-templates#266]
When trying to install email-templates I get the following error

`c:\src\now\server>npm i email-templates`

> coffee-script@1.12.8 postinstall c:\src\now\server\node_modules\coffee-script
> node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'

[eval]:1
'if
^^^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:78:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:571:32)
    at Immediate.<anonymous> (bootstrap_node.js:383:29)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

It seems that the version 1.12.8 of coffee-script was released just 5 hours ago and this seems to break. Here is the link to the repo: https://github.com/jashkenas/coffeescript/releases

**Comment by niftylettuce** [comment]
thanks for letting me know @biiit, hopefully this is resolved soon

**Comment by biiit** [comment]
As a workaround the suggested from the linked issue works:

**Comment by niftylettuce** [comment]
Per the issue linked above it is now resolved
