### ISSUE TITLE
Email Template send in secure SMTP mode

### ISSUE THREAD

**Issue by newkillerbeast2017** [niftylettuce/email-templates#270]
I am trying to send email over secure mode. Following is the way I try to create the smtp connection:

```
const emailTemplate = new EmailTemplate({
    secureConnection: true,
    secure: true,
    message: {
        from: process.env.MAIL_FROM
    },
    transport: {
        host: process.env.MAIL_HOST,
        port: process.env.MAIL_PORT,
        auth: {
            user: process.env.MAIL_USERNAME,
            pass: process.env.MAIL_PASSWORD
        }
    }
});
```

Notice I tried both `secure:true` as well `secureConnection:true`. But following is the error I am receive:

```
(node:5764) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Greeting never received
[1] (node:5764) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by newkillerbeast2017** [comment]
@niftylettuce any help?

**Comment by niftylettuce** [comment]
@newkillerbeast2017 can you please share a complete/full example?   how are you sending the messages?  what version of email-templates are you using?  what version of node are you using?

in the error you shared it shows that you are not catching a promise error

**Comment by newkillerbeast2017** [comment]
@niftylettuce  My complete code:

`mailer.ts`:
```
import * as EmailTemplate from 'email-templates';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.load({ path: '.env' });

const emailTemplate = new EmailTemplate({
    secure: true,
    message: {
        from: process.env.MAIL_FROM
    },
    transport: {
        host: process.env.MAIL_HOST,
        port: process.env.MAIL_PORT,
        auth: {
            user: process.env.MAIL_USERNAME,
            pass: process.env.MAIL_PASSWORD
        }
    }
});

export function sendVerficationLink(obj) {
    return emailTemplate.send({
        template: path.join('../src/mailers/templates', 'confirmation-mail'),
        message: {
            to: obj.email
        },
        locals: {
            name: obj.first_name + " " + obj.last_name,
            token: obj.token
        }
    });
};
```

And in my controller, I call it like:

`userctrl.ts`:
```
import * as mailer from '../mailers/mailers';
....
// On user register
mailer.sendVerficationLink(obj);
....
```

In my `.env` file:
```
MAIL_FROM=no-reply@xxx.com
MAIL_HOST=xxx.com
MAIL_PORT=465
MAIL_USERNAME=no-reply@xxx.com
MAIL_PASSWORD=yyy
```

Email-templates version: 3.2.0
Node version: v9.2.0

**Comment by niftylettuce** [comment]
Try changing the code here of `mailer.sendVerficationLink(obj);` to:

```js
mailer.sendVerficationLink(obj).then(function(data) {
  console.log('Email sent', data);
}).catch(function(err) {
  console.log('Error occurred', err);
});
```

Then run it and share the console output (or perhaps you'll see from the output what the error is).

**Comment by niftylettuce** [comment]
Just saw your "EDIT" above, sorry GitHub doesn't ping us when edits are made to comments.

Greeting never received indicates the server never responded with HELO (a greeting) to accept the mail delivery.

I think that this is a configuration issue with your port / configuration.

Are you using a known provider https://nodemailer.com/smtp/well-known/?

You could possible use `telnet` to try to connect to the mail server using those credentials so you know it's not just a code-related or code-configuration issue.

**Comment by niftylettuce** [comment]
Closing this as this question should be posted in <https://github.com/nodemailer/nodemailer> as its an issue while configuring your transport method.  Also note that there is no `secure` option for this library.  You may want to pass that option to the transport object instead so it gets passed along to Nodemailer:

```diff
const emailTemplate = new EmailTemplate({
-  secure: true,
  message: {
    from: process.env.MAIL_FROM
  },
  transport: {
+    secure: true,
    host: process.env.MAIL_HOST,
    port: process.env.MAIL_PORT,
    auth: {
      user: process.env.MAIL_USERNAME,
      pass: process.env.MAIL_PASSWORD
    }
  }
});
```
