### ISSUE TITLE
How this module can use a source mail (Stupid Question (Maybe))

### ISSUE THREAD

**Issue by SouhaibBenFarhat** [niftylettuce/email-templates#271]
Hi guys i'm new with nodejs and for some reasons i'm using this module to send email verification to users, so my question is how this module can send mails from source to destination without asking for the necessary credentials to access the sender mail and send the mail to destination.

**Comment by niftylettuce** [comment]
Could you re-phrase your question or simplify?  Or give an example/analogy?  Can you give an example in code as to what you'd like to achieve?  It's totally fine that you are new, no need to preface your question with that - we were all new at one point!

**Comment by SouhaibBenFarhat** [comment]
normally to send mail we need to login into the sender messaging account, i was wondering how this module can send mails without accessing the send account,

const email = new Email({
  message: {
    from: 'niftylettuce@gmail.com'
**//password???**

  },
//other stuff....

**Comment by niftylettuce** [comment]
You can't do that... that would be a big security flaw
