### ISSUE TITLE
How to use attachments?

### ISSUE THREAD

**Issue by thatisuday** [niftylettuce/email-templates#272]
I want to send some files with the email? Where to put them?

**Comment by niftylettuce** [comment]
in the `message` object in this example you'll need to add property
`attachments` which is an Array

https://github.com/niftylettuce/email-templates/blob/master/README.md#basic

please see Nodemailer docs at this page for more info:

https://nodemailer.com/message/attachments/

**Comment by thatisuday** [comment]
@niftylettuce Thanks a lot. Great work.

**Comment by thatisuday** [comment]
@niftylettuce It will be great if you can update Readme regarding this

**Comment by niftylettuce** [comment]
Hi @thatisuday thanks for letting me know.  I've done so, please see <https://github.com/niftylettuce/email-templates#attachments>.

If you spot any errors please advise.  Thanks!

**Comment by thatisuday** [comment]
Great. Is there any way we can add attachments to `email.send` rather than
new `Email` instance. Because, in my case attachments can vary depending on
whom to send. Is there any provision for that in future release?


- - - - - - - - - - - - - - - - - - - - -

Best Regards,

*UDAY HIWARALE*
CO-FOUNDER/CTO | GLAMPX.COM


CRM/NETWORK FOR FASHION MEDIA AGENCIES
help@glampx.com / +91-011-4948-2967

<https://www.facebook.com/GlamPX/> <https://www.instagram.com/glampx/>
<help@glampx.com> <https://glampx.com>

**Comment by niftylettuce** [comment]
Yes just include it in `email.send` not when making `new Email` and it will be individual

**Comment by thatisuday** [comment]
Ok. Thanks.


- - - - - - - - - - - - - - - - - - - - -

Best Regards,

*UDAY HIWARALE*
CO-FOUNDER/CTO | GLAMPX.COM


CRM/NETWORK FOR FASHION MEDIA AGENCIES
help@glampx.com / +91-011-4948-2967

<https://www.facebook.com/GlamPX/> <https://www.instagram.com/glampx/>
<help@glampx.com> <https://glampx.com>

**Comment by thatisuday** [comment]
@niftylettuce Nodemailer attachments are working except url or with `href` option. https://nodemailer.com/message/attachments/ Can you please check this?

**Comment by thatisuday** [comment]
@niftylettuce I am getting this in preview but no attachment receive when tried to send to gmail.

![image](https://user-images.githubusercontent.com/5711821/34882592-1294fd10-f7dd-11e7-8c6d-9e919e5586a1.png)

**Comment by thatisuday** [comment]
Problem seems to be with nodemailer itself.

**Comment by niftylettuce** [comment]
okay keep posted here if you find solution, thank you
