### ISSUE TITLE
Email and Subject are empty

### ISSUE THREAD

**Issue by kfadli** [niftylettuce/email-templates#273]
Hi, i'm testing email-template for send html templated emails and it works great on local.
But i don't understand why on my dev server (remote) i receive empty mail (subject and body).

My pug files are in same directory, i tried to set all permissions just to be sure.

Can i have any solutions or tricks to debug my specific problem ?

**Comment by makstr** [comment]
seems like a issue with paths, check the cwd of the script on your dev server

**Comment by niftylettuce** [comment]
you can run script with `DEBUG=email-templates node app.js`

**Comment by kfadli** [comment]
Thanks @niftylettuce and @makstr, with the DEBUG I could see that the file 'text.pug' was missing.

I did not think it was necessary since it did not ask me before.

I only had the files 'html.pug' and 'subject.pug', I created an empty file named 'text.pug' and everything works.

**Comment by niftylettuce** [comment]
@kfadli you shouldn't need to have a text file, I saw your comment earlier you revised - you should be able to have just a subject + html file and no text file as long as you have `htmlToText: true` option (which true is the default anyways)?

**Comment by kfadli** [comment]
I modified my comment because I realized my mistake. The missing 'text.pug' file error was a simple warning. I thought I solved the problem by adding the empty file but it worked because I start nodejs from his working directory. 
I update my launch script (forever) and everything went back to normal. it was not 'email-template s' issues that's why i closed it :)

**Comment by niftylettuce** [comment]
awesome, thanks for following up - just wanted to make sure there wasn't a bug somewhere.  thanks for using this package.
