### ISSUE TITLE
Possible to send pre-rendered template

### ISSUE THREAD

**Issue by sean-hill** [niftylettuce/email-templates#277]
Hey! I have two separate services, one that renders the email template, and one that sends it. Is it possible to send a HTML string to the `send()` function instead of having to specify a path to a template?

**Comment by niftylettuce** [comment]
@sean-hill currently it isn't, but maybe you'd be interested in submitting a pull request to add this?

you could do it in many was, but one might be to set `template: false` and then just pass in a `message` object with html and/or text properties

**Comment by niftylettuce** [comment]
@sean-hill a temporary workaround would be to just make a blank/empty template and then just pass `message` object to `send()` and include `html` and `text` and any others you want to manually specify like `subject`.  these won't get overwritten if they're already set, see <https://github.com/niftylettuce/email-templates/blob/master/src/index.js#L208>.

**Comment by sean-hill** [comment]
Perfect thank you!
