### ISSUE TITLE
How to remove function render text and subject?

### ISSUE THREAD

**Issue by juragandotid** [niftylettuce/email-templates#281]
Can i'm remove function render text and subject, only render html?

i'm using this : 

const Email = require('email-templates');

const email = new Email({
  message: {
    from: 'niftylettuce@gmail.com'
  },
  // uncomment below to send emails in development/test env:
  // send: true
  transport: {
    jsonTransport: true
  }
});

email
  .send({
    template: 'mars',
    message: {
      to: 'elon@spacex.com'
    },
    locals: {
      name: 'Elon'
    }
  })
  .then(console.log)
  .catch(console.error); 

Thank you.

**Comment by niftylettuce** [comment]
@juragandotid if you just want to render an HTML string from your template <https://github.com/niftylettuce/email-templates#render-html-andor-text>
