### ISSUE TITLE
How to remove  "- *|MC_PREVIEW_TEXT|*"  from 

### ISSUE THREAD

**Issue by borisyordanov** [niftylettuce/email-templates#292]
This text `- *|MC_PREVIEW_TEXT|*` shows up both in gmail and yahoo mail, when viewing the emails list. Once you open the email it is not visible. How can i stop it from showing up?

![image](https://user-images.githubusercontent.com/12392666/37821764-cace8616-2e84-11e8-9a63-0e338f5b0629.png)

![image](https://user-images.githubusercontent.com/12392666/37821784-d670e162-2e84-11e8-837d-dd439d6567b8.png)

**Comment by niftylettuce** [comment]
Can you share with me your template?

Are you using MailChimp?

**Comment by borisyordanov** [comment]
@niftylettuce Sorry for not responding! I am using MailChimp and this was indeed what was causing that text to appear, due to this tag
```
    <title>*|MC:SUBJECT|*</title>
```
