### ISSUE TITLE
How do I change defult template folder "emails" to "email_templates"

### ISSUE THREAD

**Issue by nicolasxu** [niftylettuce/email-templates#297]
.
├── app.js
└── emails
    └── mars
        ├── html.pug
        └── subject.pug

to 
├── app.js
└── emails_templates
    └── mars
        ├── html.pug
        └── subject.pug

Below code does not work:

```
  email.send({
    template:'/email_template/account_created/html.html',
    message: {
      to: 'xu.shenxin@gmail.com'
    }, 
    locals: {
      name: 'nick xu'
    }
  })
```

**Comment by nicolasxu** [comment]
views: {
      root: path.resolve('email_template'),
      options: {
        extension: 'html',
        map: {
          html: 'htmling'
        }
      }
    }

Sorry, I answered my own question. 
Thanks!

**Comment by niftylettuce** [comment]
Great!
