### ISSUE TITLE
Debugging tips for getting the path of nunjucks extend / include 

### ISSUE THREAD

**Issue by microcipcip** [niftylettuce/email-templates#298]
Hi, I am trying for hours to get nunjucks **extend** and **include** to work. I think I am missing the right path but have no idea how to debug it. Is there a way to see the full path of an include?

```
// structure
/utils/email.js
/templates/emails/default/html.njk
/templates/emails/default/fileToInclude.njk

// inside html.njk
{% include "./content.njk" %} // doesn't work
{% include "content.njk" %} // doesn't work

// config inside email.js
new Email({
  views: {
    root: 'templates/emails/',
    options: { extension: 'njk' }
  }
  ...
})

// 
email.send({
  template: 'default'
  ...
})
```

**Comment by microcipcip** [comment]
Hi, I have managed to find the right path, is from the root of the app. Why is not relative to what I have specified in the `views.root` object?

```
{% include "templates/emails/default/content.njk" %} // works
```

**Comment by niftylettuce** [comment]
@microcipcip have you been able to find this out?  I would check `consolidate` and its usage with `nunjucks`.

**Comment by microcipcip** [comment]
@niftylettuce so email-templates does not alter the path? It is a issue coming from consolidate?
