### ISSUE TITLE
Get email body after send

### ISSUE THREAD

**Issue by felipe-pereira** [niftylettuce/email-templates#299]
Hi, I'm using the lib like this:

```
emailSender
    .send({
        template: 'forgotPassword',
        message: {
            to: email, subject: 'Password Reset'
        },
        locals: {
            name: name, token: tokenUrl
        }
    })
    .then(cb)
    .catch(cb);
```
For testing purposes I would like to check that the generated email html has the token, so I need the render result passed to `cb`

I checked what's returned there and got this (no what I need):

```
{ accepted: [ 'to@email.com' ],
  rejected: [],
  envelopeTime: 1087,
  messageTime: 1033,
  messageSize: 1365,
  response: '250 2.0.0 OK ---------uah.42 - gsmtp',
  envelope: { from: 'from@email.com', to: [ 'to@email.com' ] },
  messageId: '<-----------------------@email.com>' }


```

How can I get the email body there? (I only need it when env is test, so using a flag for this would be great)

**Comment by niftylettuce** [comment]
Yeah I agree this would be amazing to have - let me take a look here

**Comment by niftylettuce** [comment]
I filed an issue with Nodemailer (the core package we use) [here](https://github.com/nodemailer/nodemailer/issues/877), but I will patch in the interim for you.  One moment.

**Comment by niftylettuce** [comment]
Please install `v3.6.1` of `email-templates` for support via `npm install email-templates@latest` or `yarn add email-templates@latest`.  I've provided documentation for how to get access to the message rendered (see [Inspect Message](https://github.com/niftylettuce/email-templates#inspect-message) under the Debugging section in the README).

cc @felipe-pereira
