### ISSUE TITLE
Question: Using email-templates within 'mailchimp'

### ISSUE THREAD

**Issue by jmillan** [niftylettuce/email-templates#300]
I see the mailchimp keyword in [package.json](https://github.com/niftylettuce/email-templates/blob/master/package.json#L64) but I've not found any reference in the README nor in the code.

Is there any documentation or example on how to use this module in conjunction with mailchimp?

Thanks in advance.

**Comment by niftylettuce** [comment]
Yes, MailChimp's Mandrill service is supported out of the box.  See http://nodemailer.com/smtp/well-known/, you can pass `service: 'Mandrill'` as an option for `transport` (e.g. `transport: { service: 'Mandrill', auth: { ... } }`).

If you want to use MailChimp API directly, please see <https://github.com/thorning/node-mailchimp>.

**Comment by jmillan** [comment]
Thanks
