### ISSUE TITLE
Jest integration

### ISSUE THREAD

**Issue by gcperrin** [niftylettuce/email-templates#304]
Beginning an integration of a customer codebase with Jest for testing.

Email-templates (and really I believe the dependency fs-extra) is failing on import/require for some reason. Note that our use of the package for email/templating has been running in production just fine. It only fails within the test runner. At first I thought it might be a path issue with the templates but after further digging it is actually failing on import/require. 

Snippet of the error below for consideration

Thanks,
G

<img width="977" alt="screen shot 2018-06-07 at 1 37 15 pm" src="https://user-images.githubusercontent.com/488909/41122305-54ad7e28-6a58-11e8-9553-bcd265a3807e.png">
@pmpbar

**Comment by niftylettuce** [comment]
I believe I've solved this for you in the latest version `v4.0.3` of `email-templates`! (hopefully 🤞 ) 

Seems to be possibly related to <https://github.com/facebook/jest/issues/6399> https://github.com/isaacs/node-graceful-fs/issues/102, and https://github.com/facebook/jest/issues/5239.

I just dropped the usage of `fs-extra` (which used `graceful-fs` and that seemed to have several issues with it) so perhaps try the latest version of `email-templates`, v4.0.3+ via `yarn add email-templates@latest`.  Please confirm this is the correct version installed by opening `node_modules/email-templates/package.json` afterwards and seeing that `version` property value is `4.0.3`.

Let me know once you've installed latest version and have tried again - does the issue still persist?  Did you solve it some other way?  If so, can you please update our README here with any tips/instructions for jest configuration?

I also sent you guys an email just now in case you don't get GH notifications.

Thanks many @pmpbar @gcperrin  👏 👍

**Comment by taybartski** [comment]
Thanks Lechuga! Keep up the good work!

**Comment by niftylettuce** [comment]
this is related to #318 - there is one more dep that requires `fs-extra`, fixing now
