### ISSUE TITLE
css preprocessor support?

### ISSUE THREAD

**Issue by jamesdixon** [niftylettuce/email-templates#306]
Hi,

Does this package still support CSS preprocessors like SASS? I see a number of mentions in the issues, but can't seem to find anything in the docs.

Thank you!

**Comment by niftylettuce** [comment]
It was taken out actually because we rely on juice now - if you compile the files to CSS and reference paths it should work.  If you want to submit a pull request that adds this back in lmk - not sure if there's something like `consolidate` (what we use for templates) for css/sass/less/scss etc.

**Comment by jamesdixon** [comment]
@niftylettuce thanks for the quick reply! I'll let you know if I find anything similar to `consolidate` or decide to submit a PR.

Thanks for the great piece of software. Cheers!

**Comment by niftylettuce** [comment]
@jamesdixon would ❤️ a PR for this, I'm sure folks would love something that would compile their SASS/LESS/etc before `juice` attempts to web resource inline the assets.

**Comment by niftylettuce** [comment]
@jamesdixon any luck? I will close this probably otherwise!

**Comment by jamesdixon** [comment]
@niftylettuce not yet! I'll close for now and re-open if I ever get to it. Thanks!

**Comment by sibiraj-sr** [comment]
Preprocessor would be a great addition. We have quite a large app we are still using v2 in our app and when we tried upgrading to the recent version, it broke.

> It was taken out actually because we rely on juice now

Juice uses this package [web-resource-inliner](https://github.com/jrit/web-resource-inliner) to inline css, May be if we could make some changes to make it work with `scss/less/styl` extensions using `dart-sass`. I am not sure sure if they are accepting this change.

I am not sure if this is a right path.

**Comment by sibiraj-sr** [comment]
Just noticed `linkTransform` is available with `web-resource-inliner`. which lets us to pre-process the content. and via `webResources` we can pass it inliner from juice.

**Comment by sibiraj-sr** [comment]
This is what we did.

```js
{
  juiceResources: {
    webResources: {
      linkTransform: (content, cb) => {
        const { css } = sass.renderSync({
          file: path.resolve(__dirname, "../style.scss"), // this makes imports inside to resolve correctly
          data: content.toString(),
        });
        cb(null, css.toString());
      };
      relativeTo: root;
    }
  }
}
```
