### ISSUE TITLE
TypeError: Cannot set property 'originalMessage' of undefined

### ISSUE THREAD

**Issue by aldomatic** [niftylettuce/email-templates#308]
I get the following error below, but the email is still able to send out.

**"version": "3.6.1"**

```
at processImmediate [as _immediateCallback] (timers.js:617:5) TypeError: Cannot set property 'originalMessage' of undefined
    at /node_modules/email-templates/lib/index.js:319:31
```

**Comment by niftylettuce** [comment]
What transport are you using?

**Comment by aldomatic** [comment]
@niftylettuce  I am using SMTP as the transport from nodemailer.

**Comment by niftylettuce** [comment]
Will resolve shortly

**Comment by niftylettuce** [comment]
I've emailed @andris9 to try to help out here @aldomatic - I don't see anything in the SMTP nodemailer transport that would signal to me that `info` response (aka `res` in our repo here) would be `undefined`.  Can you provide what version of `nodemailer` and `email-templates` you are using?

**Comment by niftylettuce** [comment]
closing for now until I hear more info from @aldomatic
