### ISSUE TITLE
css not applied

### ISSUE THREAD

**Issue by omarsafwany** [niftylettuce/email-templates#310]
I tried to apply css as stated [here](https://github.com/niftylettuce/email-templates#automatic-inline-css-via-stylesheets) but no style appears in the head after rendering. Here's how I am trying to it.

`.js file`
```javascript
const viewsDir = `${__dirname}/Views`;
const template = new EmailTemplates({
    views: {
        root: viewsDir,
        options: {
                    extension: 'ejs',
               },
         },
          juice: true,
           juiceResources: {
           preserveImportant: true,
           webResources: {
                     relativeTo: path.resolve(viewsDir),
            }
    }
});
```

In the `.ejs` file, I have added:
 `<link rel="stylesheet" href="/style.css" data-inline="data-inline">` 
to the `head` tag.

**Comment by niftylettuce** [comment]
You may need the path to be `href="style.css"` as opposed to `/style.css`.

**Comment by omarsafwany** [comment]
@niftylettuce still same issue. I tried to print the render result but I found the `link` tag has disappeared.

**Comment by niftylettuce** [comment]
Perhaps set `const dir = path.resolve(viewsDir)` and then `console.log('dir', dir);` to make sure that the path to the `viewsDir` is correct.  Sometimes it is different based off what directory you start the process from.

**Comment by omarsafwany** [comment]
The `dir` starts from the `Applications` folder on macOS till the `View` folder. I am not getting any warning stating the path is incorrect.

**Comment by omarsafwany** [comment]
<img width="1440" alt="screen shot 2018-07-12 at 9 30 53 pm" src="https://user-images.githubusercontent.com/5818047/42654991-df170f38-861a-11e8-9cef-e264a3b6929e.png">

Check the screenshot

**Comment by niftylettuce** [comment]
right below line 29 do a `console.log('viewsDir', viewsDir);` and `console.log('dir', dir);` -- are the paths outputted correct?  I would double check.

**Comment by niftylettuce** [comment]
I believe you can also run `DEBUG=* node app.js` to run your app with DEBUG flag in order to get verbose information on the console output from juice and email-templates, which will help you debug further.

**Comment by omarsafwany** [comment]
They are exactly the same.
```
/Applications/Workspace/notification-templates/src/Platforms/Email/Applications/CrowdAnalyzer/HelloWorld/Views
/Applications/Workspace/notification-templates/src/Platforms/Email/Applications/CrowdAnalyzer/HelloWorld/Views
```

**Comment by niftylettuce** [comment]
Do you get output with `DEBUG=* node app`?  What is output when an email is attempted to be rendered?

**Comment by omarsafwany** [comment]
I tried to hard code the css between `style` tags in the `head` in the template but nothing appears in the output. I applied the debug flag but got nothing suspicious . In the 2nd attachment, you would find the `head` tag containing only `meta` tag without the anything regarding to the style.
<img width="1440" alt="screen shot 2018-07-12 at 9 43 10 pm" src="https://user-images.githubusercontent.com/5818047/42655477-a1fa8218-861c-11e8-9adb-617bc551e745.png">
<img width="1440" alt="screen shot 2018-07-12 at 9 43 21 pm" src="https://user-images.githubusercontent.com/5818047/42655478-a21c6572-861c-11e8-84ec-dbc7712d8c31.png">

**Comment by omarsafwany** [comment]
@niftylettuce Did you find anything?

**Comment by niftylettuce** [comment]
No, but if you can make a reproducible test case I can give this more attention then.

**Comment by vikkio88** [comment]
I know that I am like 1 year and a half late to the party, but I had this error and I fixed it.

seems like you nested this
```json

juice: true,
juiceResources: {
  preserveImportant: true,
  webResources: {
    relativeTo: path.resolve(viewsDir),
  }
}
```

under `views`

Instead on the example code on the docs is on the root object. This might have been the error.
