### ISSUE TITLE
Allow to override message.from via send options

### ISSUE THREAD

**Issue by peterpetre** [niftylettuce/email-templates#313]
Please allow to pass message.from on send options and this should override the this.config.message.from

**Comment by niftylettuce** [comment]
@peterpetre care to submit a pull request + test?

**Comment by peterpetre** [comment]
@niftylettuce https://github.com/niftylettuce/email-templates/pull/319 its ok?

**Comment by niftylettuce** [comment]
Since this would be a breaking change, I think I'll publish with major semver version, agreed?

**Comment by niftylettuce** [comment]
@peterpetre I have just merged your work.  I updated the README and added a new section here <https://github.com/niftylettuce/email-templates#v5-breaking-changes> (might need a bit more explaining with an example - if you care to submit a PR to update this README with a code example that shows before/after issue that would be great).  email-templates@5.0.0 has been published to NPM.  Let me know if you have any issues, and thank you for your contributions to this project 👏 🎉
