### ISSUE TITLE
Running in Docker

### ISSUE THREAD

**Issue by andrewholsted** [niftylettuce/email-templates#315]
I'm using email-templates in an API I'm building. I love it. The ability to open a preview instead of sending the email is fantastic. 

I recently ported the API to run inside of a docker container. When I did that, the message preview stopped popping up in a new tab. Is there some additional configuration needed here? I confirmed the NODE_ENV is still in development and all the appropriate test email data gets generated. It just doesn't open the preview.

**Comment by niftylettuce** [comment]
I'm guessing its trying to open it in Docker.  It does write to a tmp
folder here
https://github.com/niftylettuce/preview-email/blob/master/src/index.js#L47.
You could console.log that filePath and paste it with file:// in browser as
protocol, but its running off your Docker so thats why its not working.

**Comment by niftylettuce** [comment]
@andrewholsted you'd probably have to fork `opn` and add support so it sends signal from docker to main parent somehow, really not sure how to do that

**Comment by DavyBello** [comment]
Hey @andrewholsted  did you figure out a way to preview the email from a docker container?

**Comment by wottpal** [comment]
:/ Would be interested, too @andrewholsted

**Comment by DavyBello** [comment]
I eventually gave up on the preview and instead mouted the tmp folder in the container as a volume.
Then manually opened the generated html in the browser.

**Comment by b4dnewz** [comment]
mount the entire tmp folder is the best solution, otherwise you will have to do tricky things like is described on [this guide](http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/) if you want to `open: true` from inside the container using, for example, firefox as shown in the post
