### ISSUE TITLE
%Email% Auto Grab

### ISSUE THREAD

**Issue by tomwilson454** [niftylettuce/email-templates#317]
I was directed here by @andris9 but yet to find an answer..

Please how can i set up nodemailer to automatically grab %Email% while sending mails to multiple emails.
Example : Hello %Email%
I expect the %Email% code to auto grab the receiver email.
Will appreciate your help.

**Comment by tomwilson454** [comment]
Really need help with this

**Comment by niftylettuce** [comment]
@tomwilson454 what do you mean to grab `%Email%`?  Not sure what you mean "auto-grab the receiver email".  A bit confused here if you can share more over this GitHub issue or via email niftylettuce@gmail.com I'd be glad to help.

**Comment by niftylettuce** [comment]
see your inbox

**Comment by tomwilson454** [comment]
Yes a list of receivers,sometimes like hundreds,i save them on notepad then upload them to the recipient option on the mass mailing software,so when ever each email receives the mail it automatically changes to their email.
