### ISSUE TITLE
requiring library causes memory leak due to indirect dependency on node-graceful-fs

### ISSUE THREAD

**Issue by shusson** [niftylettuce/email-templates#318]
Requiring this library multiple times causes a memory leak. It is caused by a dependency on `fs-extra` which has a dependency on `graceful-fs`. See https://github.com/isaacs/node-graceful-fs/issues/102.

**Comment by niftylettuce** [comment]
thanks, will patch right now, I patched this in another one of my projects and will do here as well

**Comment by niftylettuce** [comment]
see <https://github.com/niftylettuce/email-templates/commit/d187d532b1e6e7912bc7e49efef091b1410c8207> - I removed it from the project  but did not realize `get-paths` has it as well, fixing

**Comment by niftylettuce** [comment]
@shusson please try v4.0.4, and let me know! I just published the fix

ref:
https://github.com/niftylettuce/get-paths/commit/34c11b3627cff517f8ed5cf28db65817fe7622c4
https://github.com/niftylettuce/preview-email/commit/c8945b4e3807699b6d020b2dd3cb6781044c22c2
https://github.com/niftylettuce/preview-email/commit/3bd9121782c0d56cba422330343825e90b891143

**Comment by shusson** [comment]
Thanks @niftylettuce, fix confirmed 👍
