### ISSUE TITLE
Non basic template pathing?

### ISSUE THREAD

**Issue by marcwhitbread** [niftylettuce/email-templates#320]
Can I do something like template: 'content/some_key'? or '../content/some_key'?

**Comment by niftylettuce** [comment]
I'm not sure what you mean - can you be more elaborate with a code example?  We do expose the `send` and `render` methods.

**Comment by marcwhitbread** [comment]
Something like...
```email
  .send({
    template: 'some/path/to/mars',
    message: {
      to: 'elon@spacex.com'
    },
    locals: {
      name: 'Elon'
    }
  })```

OR

```email
  .send({
    template: '../../some/path/to/mars',
    message: {
      to: 'elon@spacex.com'
    },
    locals: {
      name: 'Elon'
    }
  })```

How does it work?

**Comment by marcwhitbread** [comment]
Awesome dude! I'll take a look and possibly go the PR route 👍 

Thanks for the quick reply!

**Comment by niftylettuce** [comment]
Actually @marcwhitbread - you might not even need a third argument!

https://nodejs.org/api/path.html#path_path_isabsolute_path

You could just use that inside the `render` method, and if it was an absolute path then it would not attempt to lookup the template 😄

**Comment by niftylettuce** [comment]
Going to re-open this- once we resolve/patch/PR we can close :smile:!

**Comment by niftylettuce** [comment]
@marcwhitbread would love a PR ❤️ !

**Comment by pke** [comment]
@niftylettuce Would that solve the issue?
https://github.com/niftylettuce/email-templates/pull/329
