### ISSUE TITLE
Error with tag img

### ISSUE THREAD

**Issue by trangnt58** [niftylettuce/email-templates#322]
Please help me. I don't know why tag `<img> `not receive attribute `src`. 
My version:` "email-templates": "^4.0.4"`
I add image in ejs 
`<img src="images/mail/icons/img2.png" alt="img" width="16">`
and config email:
```
const email = new Email({
	message: {
		from: config.MAIL_FROM
	},
	transport: smtpTransport,
	send: true,
	preview:false,
	views: {
		root: templateMailDir,
		options: {
			extension: 'ejs' 
		}
	},
	juiceResources: {
		webResources: {
			relativeTo: path.resolve(__dirname, '..'),
			images: true
		}
	}
});
```
But email that I received not have any image.  Attribute src not exists.

![capture](https://user-images.githubusercontent.com/10633534/45614604-4330d500-ba94-11e8-9b8c-4183be7aab9d.PNG)

**Comment by niftylettuce** [comment]
Can you try running with `DEBUG=*` for more verbose output?  I'm guessing it's just path issue.  Might be related to #324.

**Comment by niftylettuce** [comment]
@ivanpetrus 	you should set `images: true` as the example here shows https://github.com/niftylettuce/email-templates/issues/322#issue-360780863 and you should also use the plugin I made https://www.npmjs.com/package/nodemailer-base64-to-s3 - this will take the base64 images and upload them to S3/CloudFront for CDN cache busting via revision hashes

**Comment by kendallroth** [comment]
Interestingly enough, the initial issue here is happening to me as well. I have verified that the path is correct by adding `DEBUG=email-templates` and checking that a warning occurs with a fake image path. Images with a correct path simply have their `src` tag completely removed, rather than encoding it or embedding. Any thoughts @niftylettuce ?
