### ISSUE TITLE
templateExists can never find a folder, remove check?

### ISSUE THREAD

**Issue by pke** [niftylettuce/email-templates#330]
While upping the code coverage I am stuck with this codepath.
https://github.com/niftylettuce/email-templates/blob/a296f10818295353e9b34a196340338ac3fe406c/src/index.js#L125

To my understanding, `getPaths` will always return a file, never a folder?

```es6
if (stats.isDirectory()) {
  // a directory
  return {
    rel: path.join(rel, `index.${ext}`),
    ext
  };
}
``` 

So for folders it return `<folder>/index.ext` without further checking if this index file exists.
So the check in `templateExists()` is actually never triggered and could be removed?

**Comment by niftylettuce** [comment]
you're correct, I will be fixing this in next release

**Comment by niftylettuce** [comment]
actually @pke this is needed b/c `getPaths` will not check if the file `index.${ext}` exists.  so it is necessary in order to return false.

to write coverage for this, simply create a folder without an index file

**Comment by niftylettuce** [comment]
related to #332 - I am writing a fix so that if html || text don't exist on message then to not send email and throw an error

**Comment by niftylettuce** [comment]
actually I think you're right, I don't have much time to look right now more at this but if you want to patch please do

**Comment by pke** [comment]
I am also a bit short on time right now, need to patch a koa-joi-router-docs package to emit more OpenAPI doc infos, but will come back to this later. I already have 90% code coverage here.
