### ISSUE TITLE
html entities in subject

### ISSUE THREAD

**Issue by nloui** [niftylettuce/email-templates#341]
Hi there,

I've noticed that messages getting sent out using a subject.pug email template have html entities in them (ie if there's a " it converts it into a &quote;).  Any suggestions on how to resolve this?  I've tried to build in a replace &quot; with " within the pug template but the conversion must be happening somewhere later on.

Thanks!

**Comment by vigandrei** [comment]
I have the same issue. I'm not able to disable html entities in the subject. Any updates on this?

**Comment by niftylettuce** [comment]
Does changing the file's contents from `= 'Something'` to `!= 'Something &'
work`?

**Comment by nateq314** [comment]
any updates on this? Having the same issue here.

**Comment by nateq314** [comment]
I confirm that @niftylettuce's solution works.
Why isn't this in the Pug documentation???

**Comment by niftylettuce** [comment]
it is https://pugjs.org/language/attributes.html#unescaped-attributes
