### ISSUE TITLE
How do I disable your preview default?

### ISSUE THREAD

**Issue by nicolasxu** [niftylettuce/email-templates#343]
```
const email = new Email({
	message: {
		from: 'testtest@gmail.com',
		send: true,
		transport: emailConfig,	
		preview: false // it always pop up a preview window. I don't want to preview. 
	}
})
```

**Comment by ultrarunner** [comment]
I had to do something like this 
`        email.config.transport = nodemailer.createTransport({
          host: HOSTNAME,
          port: PORT,
          tls: {
            rejectUnauthorized: false
          }
        });
        email.config.preview = true;`
