### ISSUE TITLE
Is it possible to set handlebars partials?

### ISSUE THREAD

**Issue by zefexdeveloper** [niftylettuce/email-templates#346]
I was wondering if it's possible to set handlebars partials? I feel like I'm repeating myself a lot in the email templates, something that I could easily get rid of using partials by just including it.

Thank you

**Comment by zefexdeveloper** [comment]
@niftylettuce Why is this closed?

**Comment by binarytracer** [comment]
@zefexdeveloper i also what to know if thats possible.

basically i manage to "customized" the creation of content on this line: 
https://github.com/niftylettuce/email-templates/blob/master/src/index.js#L152

ive override the the function, what i mean is that from there maybe we can use  **all handlebars can do**. 

Ive never tried working on these idea yet.

**Comment by niftylettuce** [comment]
Specify the `partials` option in your configuration.

```js
const Email = require('email-templates');

const email = new Email({
  message: {
    from: 'niftylettuce@gmail.com'
  },
  transport: {
    jsonTransport: true
  },
  views: {
    options: {
      partials: {
        myPartial: 'partials/myPartial'
      }
    }
  }
});
```

Source: https://github.com/tj/consolidate.js/blob/master/lib/consolidate.js#L872-L874

Ref: https://github.com/tj/consolidate.js/issues/252

**Comment by niftylettuce** [comment]
If this works please submit PR to this repo's README with an example.  Thank you.

**Comment by binarytracer** [comment]
seems that approach is not working anymore,

i tried this definition
```js
new EmailTemplate({
  htmlToText: false,
  views: {
    root: path.resolve('emailing/views'),
    options: {
      extension: 'hbs',
      partials: {
        samplePartial: '---just-a-simple-text----',
      }
  },
  },
});
```
**i got this error**
```js
UnhandledPromiseRejectionWarning: Error: The partial samplePartial could not be found
    at Object.invokePartial (/home/meegle/tools/node_modules/handlebars/dist/cjs/handlebars/runtime.js:281:11)
    at Object.invokePartialWrapper [as invokePartial] (/home/meegle/tools/node_modules/handlebars/dist/cjs/handlebars/runtime.js:68:39)
    at Object.eval [as main] (eval at createFunctionContext (/home/meegle/tools/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:257:23), <anonymous>:8:28)

```
it seems it cant detect the partial being registered, 
im following this example here

**https://handlebarsjs.com/partials.html**

**Comment by LitvinenkoEvgeny** [comment]
Yeah after debugging i see that partials doesn't pass to handlebars engine at all
``
    "email-templates": "^8.0.2",
```
![image](https://user-images.githubusercontent.com/12531457/102387918-70112100-3fea-11eb-9084-77d43b17cf1c.png)
