### ISSUE TITLE
allow specifying only one css file

### ISSUE THREAD

**Issue by weisjohn** [niftylettuce/email-templates#35]
Instead of having a CSS file for each mail template folder, I'd like to specify just one CSS file for all the directories. (In my case, http://zurb.com/playground/responsive-email-templates has a separate CSS file)

**Comment by dantman** [comment]
I think the ideal fix for this would be the same one that would fix #135. Using `juiceResources` so that juice will inline linked stylesheets.

Then you'll have complete control over the stylesheets used in your templates by adding `<link>`s to whatever files you want imported.

**Comment by niftylettuce** [comment]
see v3.x, there's an example in readme showing how you can simply use one css file in <head> section

<https://github.com/niftylettuce/email-templates#automatic-inline-css-via-stylesheets>
