### ISSUE TITLE
relativeTo template folder 

### ISSUE THREAD

**Issue by gibson** [niftylettuce/email-templates#364]
How can a set ` relativeTo:` to current template folder, because every template can use own images 

![Screenshot 2019-06-19 at 16 31 34](https://user-images.githubusercontent.com/140022/59762063-c2676980-92af-11e9-8a9e-d833d9435817.png)

**Comment by niftylettuce** [comment]
I would suggest just doing multiple instances of `new Email`, or you could submit a PR.
