### ISSUE TITLE
Erreur non dev environments

### ISSUE THREAD

**Issue by nithramus** [niftylettuce/email-templates#365]
I just updated to the last email-templates version.
When my NODE_ENV is set to "test" or "development"
returned object is:
`
{
      from: 'KeobizTest < test@keobiz.fr >',
      to: 'success@simulator.amazonses.com',
      attachments: [],
      subject: 'subject',
      html:
        '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <body>test variable\n    </body>\n  </head>\n</html>',
      text: 'text', 
    }
`
 

On other environments:
 `
{
      from: 'KeobizTest < test@keobiz.fr >',
      to: 'success@simulator.amazonses.com',
      attachments: [],
      subject: 'subject',
      html: <!DOCTYPE html>\n<html lang="en">\n  <head>\n    <body>test variable\n    </body>\n  </head>\n</html>',
text: '<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <body>test variable\n    </body>\n  </head>\n</html>'
}
`
--> It look like the fields "text" is not well rendered on non dev environnement

**Comment by niftylettuce** [comment]
Please provide a reproducible example if you still have this issue
