### ISSUE TITLE
renderAll doesn't render all 

### ISSUE THREAD

**Issue by simllll** [niftylettuce/email-templates#366]
I was expecting that renderAll will render all files in one directory, but instead it's hardcoded to text,html and subject.
Just in case someone else runs into this too ;) Would be great to add this to the documentation, or even better if there would be an option to add some custom templates.

Regards
Simon

**Comment by niftylettuce** [comment]
What else would you be rendering besides text/html/subject?

**Comment by niftylettuce** [comment]
Let me know!

**Comment by simllll** [comment]
In my case I use it for deeplinks for example.

Regards

**Comment by niftylettuce** [comment]
Can you share a snippet/example?  I'm not sure what you're referring to for deeplinks.  I only know that Nodemailer supports `html`, `text`, and `subject`.

**Comment by simllll** [comment]
I use only the render part of the library, and I use it for all type of notifications. Besides email this is apn, fcm, webpush, redis pubsub,.. 
E.g. the render part looks currently something like this:

```
const rendered = await (template as any).renderAll(contentType, data);

		if (contentType === 'push') {
			rendered.deeplink = await template.checkAndRender('deeplink', contentType, data);
		}

		return rendered;
```

Regards

**Comment by niftylettuce** [comment]
I think that may be out of the scope of this library, since we use `consolidate` internally, it may be easier for you to directly use it.

Ref: https://github.com/tj/consolidate.js

PR is welcome though
