### ISSUE TITLE
Multiline message html

### ISSUE THREAD

**Issue by 1Map** [niftylettuce/email-templates#368]
**I have a message locals variable like:**
```
	locals: {
		message: 'Line 1<br>Line 2<br>Line 3'
	}
```
**My PUG is as follow:**
```
	p
		b Message is as follow:
	p
		| #{message}
```

**Problem is that the HTML renders the message as:**
`Line 1<br>Line 2<br>Line 3`

**but what I want to see is:**
```
Line 1
Line 2
Line 3
```

**Comment by niftylettuce** [comment]
Change your pug to be:

```pug
	p
		b Message is as follow:
	p
		| !{message}
```

Note that change from `#{message}` to `!{message}`.
