### ISSUE TITLE
Lodash Security Vulnerability

### ISSUE THREAD

**Issue by JonathanJamesRasmussen** [niftylettuce/email-templates#370]
There is a high-severity security bug in Lodash that was recently published:

https://github.com/lodash/lodash/pull/4336

It appears as though this tool isn't updated to use this patch yet.

**Comment by niftylettuce** [comment]
TBH anyone that is affected by this has poor architecture and a poor sense of security.  PR is welcome.  I occasionally version bump deps.

**Comment by JonathanJamesRasmussen** [comment]
Thanks for clarifying. I was going based on a GitHub security alert, but after running NPM audit, it seems to be a non-issue.
