### ISSUE TITLE
RenderAll not applying styles

### ISSUE THREAD

**Issue by dreamcatcha** [niftylettuce/email-templates#371]
I have upgraded to 6.0.0 and learned I had to use renderAll to create template from multiple files. 
files including html.hbs, text.hbs, subject.hbs, style.hbs which worked in previous version, Im not sure why it doesn't work in the latest version

I added the following to the head section of the html.hbs file

`link(rel="stylesheet", href="style.css", data-inline)`

And the following is my Email config

```
new Email({
    views: { 
        options: { extension: 'hbs' },
        root: myTemplateDir
    },
    dkim: {
        domainName: 'example.com', 
        keySelector: 'default', 
        privateKey: dkimPrivateKey, 
        cacheDir: '/tmp', 
        cacheTreshold: 100 * 1024
    },
    juice: true,
    juiceResources: {
        preserveImportant: true,
        webResources: {
            relativeTo: myTemplateDir
        }
    }
});
```

Im not sure what im missing

**Comment by niftylettuce** [comment]
Can you make a test repository on GitHub that shows this isn't working?
