### ISSUE TITLE
xdg-open spawn error

### ISSUE THREAD

**Issue by paul-gpsit** [niftylettuce/email-templates#372]
We are using email-templates in an AWS lambda function. The template files are hosted in an S3 bucket. In the lambda, we download the template to a local temp folder in the lambda.

When I try to call the send method, it errors out.

When using v5.0.5, it gives this error object:
"error": {
   "code": "EACCES",
   "errno": "EACCES",
   "syscall": "spawn"
         }

When I tried using v6.0.0, it gave this error:
spawn xdg-open ENOENT

The options being passed in are:
{
    "template": "/tmp/0BaZ4XBBo/default-test",
    "message": {
        "to": "my@email.address",
        "subject": "Test",
        "headers": {
            "X-SES-CONFIGURATION-SET": "Engagement"
        },
        "ref": [
            "a reference"
        ],
        "template": "default-test"
    },
    "locals": {
        "message": {
            "kpins": [
                {
                    "kpin": "1234",
                    "id": "123444"
                }
            ]
        }
    }
}

**Comment by niftylettuce** [comment]
PR welcome that would fix this, I don't really use nor support Lambda
